Repository meilisearch/meilisearch-symfony, pull requests merged in 2020-07, with the labels that each got.

#3 Update version for the next release (v0.1.1) in MeiliSearchBundle.php
  src/MeiliSearchBundle.php
Labels: skip-changelog

#10 Fix indentation style of some yml files
  .github/release-draft-template.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#8 Remame MEILISEARCH_MASTER_KEY env variable into MEILISEARCH_API_KEY
  phpunit.xml.dist
  src/Resources/config/services.xml
Labels: breaking-change

#11 Update package version from v0.1.1 to v0.2.0
  src/MeiliSearchBundle.php
Labels: skip-changelog

#16 Update CONTRIBUTING.md with issue on MacOs about Docker Environment setup
  CONTRIBUTING.md
Labels: skip-changelog

#13 Fix clear command, checking return status code
  src/Command/MeiliSearchClearCommand.php
  tests/TestCase/CommandsTest.php
Labels: Symfony integration, help wanted
