Repository meilisearch/meilisearch-symfony, pull requests merged in 2023-05, with the labels that each got.

#247 Update README.md with self hosted bors link
  README.md
Labels: skip-changelog

#165 Add phpmd to project
  .github/workflows/tests.yml
  CONTRIBUTING.md
  composer.json
  phpmd.baseline.xml
  phpmd.xml
Labels: enhancement, stale

#250 Start fixing PHPMD issues
  src/Collection.php
  src/Command/MeilisearchClearCommand.php
  src/Command/MeilisearchCreateCommand.php
  src/Command/MeilisearchImportCommand.php
  src/DependencyInjection/MeilisearchExtension.php
  src/Services/MeilisearchService.php
Labels: enhancement

#239 Allow to configure custom serializer groups
  .github/workflows/tests.yml
  composer.json
  phpstan.neon
  phpunit.xml.dist
  src/DependencyInjection/Configuration.php
  src/SearchableEntity.php
  src/Services/MeilisearchService.php
  tests/Entity/DummyCustomGroups.php
  tests/Integration/CommandsTest.php
  tests/Unit/ConfigurationTest.php
  tests/Unit/SerializationTest.php
  tests/baseline-ignore
  tests/bootstrap.php
  tests/config/config.yaml
  tests/config/config_php7.yaml
  tests/config/meilisearch.yaml
Labels: enhancement
